apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-app
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
